close all; clear all; clc;

% Reading in data
File = readtable('FILE.csv');
% yan1 is 6 seconds long
T=File;
time = 6;

% Cleaning data so that only the x,y,z values remain
T(:,(end-13):end) = [];  % removing extra stats at the end of the table
T(:,4:6:end) = []; % removing error values
T(:,4:5:end) = []; % removing number of cams
T(:,4:4:end) = []; % removing score values


% Largest pixel coordinate in table = 1.5437e+03
% Smallest pixel coordinate in table = -261.8193

h = height(T); % Number of rows in table

ThumbPlot = plot3([T.TT_z(1),T.TIP_z(1),T.TMCP_z(1),T.TCMC_z(1),T.W_z(1)], ...
    [T.TT_x(1),T.TIP_x(1),T.TMCP_x(1),T.TCMC_x(1),T.W_x(1)], ...
    [T.TT_y(1),T.TIP_y(1),T.TMCP_y(1),T.TCMC_y(1),T.W_y(1)], ...
    '-o', 'MarkerSize',3,'MarkerFaceColor','r');
axis([800 1600 -300 300 -300 300]) % Setting plot borders
hold on
xlabel('x')
ylabel('y')
zlabel('z')
title('output')

%Setting camera angle (and reversing the y in relation to the x and z values)
set(gca, 'XDir','reverse')
set(gca, 'ZDir','reverse')

myVideo = VideoWriter('output.avi');
myVideo.FrameRate = 30;
open(myVideo)

IndexPlot = plot3([T.IT_z(1),T.IDIP_z(1),T.IPIP_z(1),T.IMCP_z(1),T.W_z(1)], ...
    [T.IT_x(1),T.IDIP_x(1),T.IPIP_x(1),T.IMCP_x(1),T.W_x(1)], ...
    [T.IT_y(1),T.IDIP_y(1),T.IPIP_y(1),T.IMCP_y(1),T.W_y(1)], ...
    '-o', 'MarkerSize',3,'MarkerFaceColor','m');
MiddlePlot = plot3([T.MT_z(1),T.MDIP_z(1),T.MPIP_z(1),T.MMCP_z(1),T.W_z(1)], ...
    [T.MT_x(1),T.MDIP_x(1),T.MPIP_x(1),T.MMCP_x(1),T.W_x(1)], ...
    [T.MT_y(1),T.MDIP_y(1),T.MPIP_y(1),T.MMCP_y(1),T.W_y(1)], ...
    '-o', 'MarkerSize',3,'MarkerFaceColor','b');
RingPlot = plot3([T.RT_z(1),T.RDIP_z(1),T.RPIP_z(1),T.RMCP_z(1),T.W_z(1)], ...
    [T.RT_x(1),T.RDIP_x(1),T.RPIP_x(1),T.RMCP_x(1),T.W_x(1)], ...
    [T.RT_y(1),T.RDIP_y(1),T.RPIP_y(1),T.RMCP_y(1),T.W_y(1)], ...
    '-o', 'MarkerSize',3,'MarkerFaceColor','c');
LittlePlot = plot3([T.LT_z(1),T.LDIP_z(1),T.LPIP_z(1),T.LMCP_z(1),T.W_z(1)], ...
    [T.LT_x(1),T.LDIP_x(1),T.LPIP_x(1),T.LMCP_x(1),T.W_x(1)], ...
    [T.LT_y(1),T.LDIP_y(1),T.LPIP_y(1),T.LMCP_y(1),T.W_y(1)], ...
    '-o', 'MarkerSize',3,'MarkerFaceColor','g');
Arm1Plot = plot3([T.W_z(1),T.IE_z(1),T.IS_z(1),T.C_z(1)], ...
    [T.W_x(1),T.IE_x(1),T.IS_x(1),T.C_x(1)], ...
    [T.W_y(1),T.IE_y(1),T.IS_y(1),T.C_y(1)], ...
    '-o', 'MarkerSize',3,'MarkerFaceColor',	"#D95319");
Arm2Plot = plot3([T.W_z(1),T.OE_z(1),T.OS_z(1),T.C_z(1)], ...
    [T.W_x(1),T.OE_x(1),T.OS_x(1),T.C_x(1)], ...
    [T.W_y(1),T.OE_y(1),T.OS_y(1),T.C_y(1)], ...
    '-o', 'MarkerSize',3,'MarkerFaceColor',	"#7E2F8E");
% CupPlot = plot3([T.CupTopRight_z(1),T.CupBottomLeft_z(1),T.HandleBottom_z(1),T.HandleTop_z(1)], ...
%     [T.CupTopRight_x(1),T.CupBottomLeft_x(1),T.HandleBottom_x(1),T.HandleTop_x(1)], ...
%     [T.CupTopRight_y(1),T.CupBottomLeft_y(1),T.HandleBottom_y(1),T.HandleTop_y(1)], ...
%     '-o', 'MarkerSize',3,'MarkerFaceColor',	"k");

frame = getframe(gcf);
writeVideo(myVideo, frame);

% Animating the plot
for i = 2:h
    pause(time/h)
    set(ThumbPlot, 'ZData', [T.TT_y(1),T.TIP_y(i),T.TMCP_y(i),T.TCMC_y(i),T.W_y(i)], ...
        'XData', [T.TT_z(1),T.TIP_z(i),T.TMCP_z(i),T.TCMC_z(i),T.W_z(i)], ...
        'YData', [T.TT_x(i),T.TIP_x(i),T.TMCP_x(i),T.TCMC_x(i),T.W_x(i)]);
    set(IndexPlot,'ZData', [T.IT_y(i),T.IDIP_y(i),T.IPIP_y(i),T.IMCP_y(i),T.W_y(i)], ...
        'XData', [T.IT_z(i),T.IDIP_z(i),T.IPIP_z(i),T.IMCP_z(i),T.W_z(i)], ...
        'YData', [T.IT_x(i),T.IDIP_x(i),T.IPIP_x(i),T.IMCP_x(i),T.W_x(i)]);
    set(MiddlePlot, 'ZData', [T.MT_y(i),T.MDIP_y(i),T.MPIP_y(i),T.MMCP_y(i),T.W_y(i)], ...
        'XData', [T.MT_z(i),T.MDIP_z(i),T.MPIP_z(i),T.MMCP_z(i),T.W_z(i)], ...
        'YData', [T.MT_x(i),T.MDIP_x(i),T.MPIP_x(i),T.MMCP_x(i),T.W_x(i)]);
    set(RingPlot, 'ZData', [T.RT_y(i),T.RDIP_y(i),T.RPIP_y(i),T.RMCP_y(i),T.W_y(i)], ...
        'XData', [T.RT_z(i),T.RDIP_z(i),T.RPIP_z(i),T.RMCP_z(i),T.W_z(i)], ...
        'YData', [T.RT_x(i),T.RDIP_x(i),T.RPIP_x(i),T.RMCP_x(i),T.W_x(i)]);
    set(LittlePlot, 'ZData', [T.LT_y(i),T.LDIP_y(i),T.LPIP_y(i),T.LMCP_y(i),T.W_y(i)], ...
        'XData', [T.LT_z(i),T.LDIP_z(i),T.LPIP_z(i),T.LMCP_z(i),T.W_z(i)], ...
        'YData', [T.LT_x(i),T.LDIP_x(i),T.LPIP_x(i),T.LMCP_x(i),T.W_x(i)]);
    set(Arm1Plot, 'ZData', [T.W_y(i),T.IE_y(i),T.IS_y(i),T.C_y(i)], ...
        'XData', [T.W_z(i),T.IE_z(i),T.IS_z(i),T.C_z(i)], ...
        'YData', [T.W_x(i),T.IE_x(i),T.IS_x(i),T.C_x(i)]);
    set(Arm2Plot, 'ZData', [T.W_y(i),T.OE_y(i),T.OS_y(i),T.C_y(i)], ...
        'XData', [T.W_z(i),T.OE_z(i),T.OS_z(i),T.C_z(i)], ...
        'YData', [T.W_x(i),T.OE_x(i),T.OS_x(i),T.C_x(i)]);
%     set(CupPlot, 'ZData', [T.CupTopRight_z(i),T.CupBottomLeft_z(i),T.HandleBottom_z(i),T.HandleTop_z(i)], ...
%         'XData', [T.CupTopRight_x(i),T.CupBottomLeft_x(i),T.HandleBottom_x(i),T.HandleTop_x(i)], ...
%         'YData', [T.CupTopRight_y(i),T.CupBottomLeft_y(i),T.HandleBottom_y(i),T.HandleTop_y(i)]);

    frame = getframe(gcf);
    writeVideo(myVideo, frame);
end

close(myVideo)