close all; clear all; clc;

% Reading in data
%File = readtable('C:\Users\czhe0008\Documents\DLCprojects\openpose\data_conversion\massive_3d\json_calib_test\3d\p19\df_3d.csv');
File = readtable('C:\Users\czhe0008\Documents\DLCprojects\openpose\data_conversion\massive_3d\3d\p19_3d_sorted\Instructions_COO4\20240809T123843-123853\df_3d.csv');
%File = readtable('C:\Users\czhe0008\Documents\DLCprojects\openpose\data_conversion\massive_3d\p16_cat\Instructions_DIG7\20240802T124716-124725_filtered.csv');
%T=File;
% If a video needs cropping:
%T(end-80:end,:) = [];
%T(1:120,:) = [];
T = File;
for i = 0:((width(T)/3)-1)
    T{:,i*3 + 1} = T{:,i*3 + 1} - File{:,67};
    T{:,i*3 + 2} = T{:,i*3 + 2} - File{:,68};
    T{:,i*3 + 3} = T{:,i*3 + 3} - File{:,69};
end


h = height(T); % Number of rows in table
startFrame = 1;

ThumbPlot = plot3([T.TT_z(startFrame),T.TIP_z(startFrame),T.TMCP_z(startFrame),T.TCMC_z(startFrame),T.RW_z(startFrame)], ...
    [T.TT_x(startFrame),T.TIP_x(startFrame),T.TMCP_x(startFrame),T.TCMC_x(startFrame),T.RW_x(startFrame)], ...
    [T.TT_y(startFrame),T.TIP_y(startFrame),T.TMCP_y(startFrame),T.TCMC_y(startFrame),T.RW_y(startFrame)], ...
    '-o', 'MarkerSize',3,'MarkerFaceColor','r');
% Default: axis([1000 2000 -400 400 -400 400]) % Setting plot borders [X, Y, Z]
%axis([1400 2200 -600 200 -600 400])
axis([-700 100 -600 200 -400 400])

% Stitch together different view points

hold on
xlabel('z (mm)')
ylabel('y (mm)')
zlabel('x (mm)')
title('Activity')

%reachPlotmeasured = plot3([reach_start, reach_end],[0,0],[0,0],'-o', 'MarkerSize',3,'MarkerFaceColor','k');
%reachPlotexpected = plot3([reach_start, reach_start-390],[0,0],[0,0],'-o', 'MarkerSize',3,'MarkerFaceColor','k');

% Setting camera angle (and reversing the y in relation to the x and z values)
set(gca, 'XDir','reverse')
set(gca, 'ZDir','reverse')
set(gca, 'fontsize',14)
set(gcf,'position',[200,200,600,570])
% Default is back view
%view([90 10]) %front view
%view([150 30]) %left side view
%view([0 90]) %top right side view
view([50 30]) %e3v834c view

myVideo = VideoWriter('video.avi');
myVideo.FrameRate = 30;
% 1-240, 280-520, 600-800, 880-1080, 1160-end
open(myVideo)

IndexPlot = plot3([T.IT_z(startFrame),T.IDIP_z(startFrame),T.IPIP_z(startFrame),T.IMCP_z(startFrame),T.RW_z(startFrame)], ...
    [T.IT_x(startFrame),T.IDIP_x(startFrame),T.IPIP_x(startFrame),T.IMCP_x(startFrame),T.RW_x(startFrame)], ...
    [T.IT_y(startFrame),T.IDIP_y(startFrame),T.IPIP_y(startFrame),T.IMCP_y(startFrame),T.RW_y(startFrame)], ...
    '-o', 'MarkerSize',3,'MarkerFaceColor','m');
MiddlePlot = plot3([T.MT_z(startFrame),T.MDIP_z(startFrame),T.MPIP_z(startFrame),T.MMCP_z(startFrame),T.RW_z(startFrame)], ...
    [T.MT_x(startFrame),T.MDIP_x(startFrame),T.MPIP_x(startFrame),T.MMCP_x(startFrame),T.RW_x(startFrame)], ...
    [T.MT_y(startFrame),T.MDIP_y(startFrame),T.MPIP_y(startFrame),T.MMCP_y(startFrame),T.RW_y(startFrame)], ...
    '-o', 'MarkerSize',3,'MarkerFaceColor','b');
RingPlot = plot3([T.RT_z(startFrame),T.RDIP_z(startFrame),T.RPIP_z(startFrame),T.RMCP_z(startFrame),T.RW_z(startFrame)], ...
    [T.RT_x(startFrame),T.RDIP_x(startFrame),T.RPIP_x(startFrame),T.RMCP_x(startFrame),T.RW_x(startFrame)], ...
    [T.RT_y(startFrame),T.RDIP_y(startFrame),T.RPIP_y(startFrame),T.RMCP_y(startFrame),T.RW_y(startFrame)], ...
    '-o', 'MarkerSize',3,'MarkerFaceColor','c');
LittlePlot = plot3([T.LT_z(startFrame),T.LDIP_z(startFrame),T.LPIP_z(startFrame),T.LMCP_z(startFrame),T.RW_z(startFrame)], ...
    [T.LT_x(startFrame),T.LDIP_x(startFrame),T.LPIP_x(startFrame),T.LMCP_x(startFrame),T.RW_x(startFrame)], ...
    [T.LT_y(startFrame),T.LDIP_y(startFrame),T.LPIP_y(startFrame),T.LMCP_y(startFrame),T.RW_y(startFrame)], ...
    '-o', 'MarkerSize',3,'MarkerFaceColor','g');
RightArmPlot = plot3([T.C_z(startFrame),T.RS_z(startFrame),T.RE_z(startFrame),T.RW_z(startFrame)], ...
     [T.C_x(startFrame),T.RS_x(startFrame),T.RE_x(startFrame),T.RW_x(startFrame)], ...
     [T.C_y(startFrame),T.RS_y(startFrame),T.RE_y(startFrame),T.RW_y(startFrame)], ...
     '-o', 'MarkerSize',3,'MarkerFaceColor',	"#D95319");
% WristPlot = plot3([T.TW_z(startFrame),T.W_z(startFrame),T.LW_z(startFrame)], ...
%     [T.TW_x(startFrame),T.W_x(startFrame),T.LW_x(startFrame)], ...
%     [T.TW_y(startFrame),T.W_y(startFrame),T.LW_y(startFrame)], ...
%     '-o', 'MarkerSize',3,'MarkerFaceColor',	"#D95319");
% Arm1Plot = plot3([T.W_z(startFrame),T.IE_z(startFrame),T.IS_z(startFrame),T.C_z(startFrame),T.S_z(startFrame)], ...
%     [T.W_x(startFrame),T.IE_x(startFrame),T.IS_x(startFrame),T.C_x(startFrame),T.S_x(startFrame)], ...
%     [T.W_y(startFrame),T.IE_y(startFrame),T.IS_y(startFrame),T.C_y(startFrame),T.S_y(startFrame)], ...
%     '-o', 'MarkerSize',3,'MarkerFaceColor',	"#EDB120");
% Arm2Plot = plot3([T.TW_z(startFrame),T.OE_z(startFrame),T.OS_z(startFrame),T.C_z(startFrame),T.S_z(startFrame)], ...
%     [T.TW_x(1),T.OE_x(startFrame),T.OS_x(startFrame),T.C_x(startFrame),T.S_x(startFrame)], ...
%     [T.TW_y(1),T.OE_y(startFrame),T.OS_y(startFrame),T.C_y(startFrame),T.S_y(startFrame)], ...
%     '-o', 'MarkerSize',3,'MarkerFaceColor',	"#7E2F8E");
% Arm3Plot = plot3([T.LW_z(startFrame),T.OE_z(startFrame),T.OS_z(startFrame),T.C_z(startFrame),T.S_z(startFrame)], ...
%     [T.LW_x(startFrame),T.OE_x(startFrame),T.OS_x(startFrame),T.C_x(startFrame),T.S_x(startFrame)], ...
%     [T.LW_y(startFrame),T.OE_y(startFrame),T.OS_y(startFrame),T.C_y(startFrame),T.S_y(startFrame)], ...
%     '-o', 'MarkerSize',3,'MarkerFaceColor',	"#77AC30");

saveas(gcf,'reach_length.png')

frame = getframe(gcf);
writeVideo(myVideo, frame);

% Animating the plot
for i = (startFrame+1):(h-3)
    set(ThumbPlot, 'ZData', [T.TT_y(i),T.TIP_y(i),T.TMCP_y(i),T.TCMC_y(i),T.RW_y(i)], ...
        'XData', [T.TT_z(i),T.TIP_z(i),T.TMCP_z(i),T.TCMC_z(i),T.RW_z(i)], ...
        'YData', [T.TT_x(i),T.TIP_x(i),T.TMCP_x(i),T.TCMC_x(i),T.RW_x(i)]);
    set(IndexPlot,'ZData', [T.IT_y(i),T.IDIP_y(i),T.IPIP_y(i),T.IMCP_y(i),T.RW_y(i)], ...
        'XData', [T.IT_z(i),T.IDIP_z(i),T.IPIP_z(i),T.IMCP_z(i),T.RW_z(i)], ...
        'YData', [T.IT_x(i),T.IDIP_x(i),T.IPIP_x(i),T.IMCP_x(i),T.RW_x(i)]);
    set(MiddlePlot, 'ZData', [T.MT_y(i),T.MDIP_y(i),T.MPIP_y(i),T.MMCP_y(i),T.RW_y(i)], ...
        'XData', [T.MT_z(i),T.MDIP_z(i),T.MPIP_z(i),T.MMCP_z(i),T.RW_z(i)], ...
        'YData', [T.MT_x(i),T.MDIP_x(i),T.MPIP_x(i),T.MMCP_x(i),T.RW_x(i)]);
    set(RingPlot, 'ZData', [T.RT_y(i),T.RDIP_y(i),T.RPIP_y(i),T.RMCP_y(i),T.RW_y(i)], ...
        'XData', [T.RT_z(i),T.RDIP_z(i),T.RPIP_z(i),T.RMCP_z(i),T.RW_z(i)], ...
        'YData', [T.RT_x(i),T.RDIP_x(i),T.RPIP_x(i),T.RMCP_x(i),T.RW_x(i)]);
    set(LittlePlot, 'ZData', [T.LT_y(i),T.LDIP_y(i),T.LPIP_y(i),T.LMCP_y(i),T.RW_y(i)], ...
        'XData', [T.LT_z(i),T.LDIP_z(i),T.LPIP_z(i),T.LMCP_z(i),T.RW_z(i)], ...
        'YData', [T.LT_x(i),T.LDIP_x(i),T.LPIP_x(i),T.LMCP_x(i),T.RW_x(i)]);
    set(RightArmPlot, 'ZData', [T.C_y(i),T.RS_y(i),T.RE_y(i),T.RW_y(i)], ...
        'XData', [T.C_z(i),T.RS_z(i),T.RE_z(i),T.RW_z(i)], ...
        'YData', [T.C_x(i),T.RS_x(i),T.RE_x(i),T.RW_x(i)]);
%     set(WristPlot, 'ZData', [T.TW_y(i),T.W_y(i),T.LW_y(i)], ...
%         'XData', [T.TW_z(i),T.W_z(i),T.LW_z(i)], ...
%         'YData', [T.TW_x(i),T.W_x(i),T.LW_x(i)]);
%     set(Arm1Plot, 'ZData', [T.W_y(i),T.IE_y(i),T.IS_y(i),T.C_y(i),T.S_y(i)], ...
%         'XData', [T.W_z(i),T.IE_z(i),T.IS_z(i),T.C_z(i),T.S_z(i)], ...
%         'YData', [T.W_x(i),T.IE_x(i),T.IS_x(i),T.C_x(i),T.S_x(i)]);
%     set(Arm2Plot, 'ZData', [T.TW_y(i),T.OE_y(i),T.OS_y(i),T.C_y(i),T.S_y(i)], ...
%         'XData', [T.TW_z(i),T.OE_z(i),T.OS_z(i),T.C_z(i),T.S_z(i)], ...
%         'YData', [T.TW_x(i),T.OE_x(i),T.OS_x(i),T.C_x(i),T.S_x(i)]);
%     set(Arm3Plot, 'ZData', [T.LW_y(i),T.OE_y(i),T.OS_y(i),T.C_y(i),T.S_y(i)], ...
%         'XData', [T.LW_z(i),T.OE_z(i),T.OS_z(i),T.C_z(i),T.S_z(i)], ...
%         'YData', [T.LW_x(i),T.OE_x(i),T.OS_x(i),T.C_x(i),T.S_x(i)]);

    frame = getframe(gcf);
    writeVideo(myVideo, frame);
end
fprintf('done')
close(myVideo)